language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
bundler_args: --without development
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "cp config/database.yml.travis config/database.yml"
  - "mysql -e 'create database aircasting_test;'"
  - "RAILS_ENV=test rake db:migrate"
script:
  - "rspec spec/spec_helper.rb spec && DISPLAY=:99.0 RAILS_ENV=test rake jasmine:headless"
